
version: '2'
services:
  node:
    image: node-develop:latest
    volumes:
      - my-app:/home/vue-projects/vpl-data-science/
    ports:
      - '5173:5173'
    networks:
      - network_final_project

networks:
  network_final_project:
    name: network_final_project
    driver: bridge

volumes:
  my-app: